---
abstract: 'Module to interface with the http://PagerDuty.com service'
author:
  - 'Oleg Kostyuk <cub@cpan.org>'
build_requires:
  Test::LWP::UserAgent: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-PagerDuty
recommends:
  JSON::XS: 0
requires:
  Class::Accessor: 0
  Error: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  URI: 0
  URI::QueryParam: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.07
